version: "3.4"

services:
  gas_oracle:
    image: omg/transaction-monitor:production-v1
    environment:
      L1_NODE_WEB3_URL: ${L1_NODE_WEB3_URL}
      L2_NODE_WEB3_URL: ${L2_NODE_WEB3_URL}
      MYSQL_HOST_URL: ${MYSQL_HOST_URL}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE_NAME: ${MYSQL_DATABASE_NAME}
      ADDRESS_MANAGER_ADDRESS: ${ADDRESS_MANAGER_ADDRESS}
      L2_MESSENGER_ADDRESS: ${L2_MESSENGER_ADDRESS}
      DEPLOYER_PRIVATE_KEY: ${DEPLOYER_PRIVATE_KEY}
      TRANSACTION_MONITOR_INTERVAL: ${TRANSACTION_MONITOR_INTERVAL}